query me {
  me {
    id
  }
}

query getUserInfo {
  me {
    name
    email
    username
    website
    bio
  }
}

mutation updateBio($bio: String!) {
  updateBio(bio: $bio) {
    bio
  }
}

mutation updateUserInfo($name: String!, $website: String!) {
  updateBaseUserInfo(name: $name, website: $website) {
    name
    website
  }
}

mutation likePark($parkPublicId: String!) {
  likePark(parkPublicId: $parkPublicId)
}

mutation addParktoBucketList($parkPublicId: String!) {
  addToBucketList(parkPublicId: $parkPublicId)
}

mutation unlikePark($parkPublicId: String!) {
  unlikePark(parkPublicId: $parkPublicId)
}

mutation removeParkFromBucketList($parkPublicId: String!) {
  removeFromBucketList(parkPublicId: $parkPublicId)
}

mutation submitReview($parkPublicId: String!, $review: String!, $rating: String!, $visitedAt: String!) {
  mutateReview(parkPublicId: $parkPublicId, review: $review, rating: $rating, visitedAt: $visitedAt)
}